# Generated by Django 3.2.21 on 2023-09-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-ranking_position']},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='tags',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='rank',
            new_name='ranking_position',
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='place',
            name='location_string',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='ranking_string',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='sub_categories',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.CharField(default='type', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(),
        ),
    ]
