# Generated by Django 3.2.21 on 2023-09-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='ranking_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
