# Generated by Django 3.2.21 on 2023-10-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='rating',
            new_name='ratings',
        ),
    ]
