# Generated by Django 3.2.21 on 2023-10-13 23:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_rename_ratings_place_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Loved It', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.CharField(default='placeholder', max_length=150),
        ),
    ]
