# Generated by Django 3.2.21 on 2023-10-19 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
