# Generated by Django 3.2.21 on 2023-11-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_review_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
