# Generated by Django 3.2.21 on 2023-11-16 21:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_alter_place_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
