# Generated by Django 3.2.21 on 2023-11-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_place_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='sub_categories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
