# Generated by Django 3.2.21 on 2023-09-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
