# Generated by Django 3.2.21 on 2023-11-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_longtitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
