# Generated by Django 3.2.21 on 2023-09-18 22:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20230918_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
