# Generated by Django 3.2.21 on 2023-09-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
