# Generated by Django 3.2.21 on 2023-09-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('trips', '0005_alter_trip_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='trip_place', to='places.Place'),
        ),
    ]
